Puraalina branch
raduchistest/es-2021 pull request #3
Opened 2021-11-08 15:58 UTC by PuraAlina97

Added Pura Alina tasks.

2021-11-08 22:22 UTC, tibict requested changes
Hey Alina! Looks good to me, you may add me as reviewer. ;-)

2021-11-11 11:05 UTC, cristiangfilip requested changes
Hey Alina! Everything is ok, you can add me as reviewer

2021-11-15 14:16 UTC, tibict approved these changes

2021-11-15 14:55 UTC, cristiangfilip approved these changes

2021-11-15 15:10 UTC, merged